In [ ]:
# Topic : 
# Data :
# try apply
# api writing
# features : Medical 
# github
# Kaggle : Problem: 

# https://www.kaggle.com/code/jetakow/home-credit-2024-starter-notebook/input

In [42]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.model_selection import train_test_split
from nltk.tokenize import word_tokenize
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from textblob import TextBlob

import os
import re
import glob

### 1. Data Gathering

In [3]:
neg_review_path = r"E:\9Dec2023\Notes\2024_3_26_Naive_Bayes\movie_reviews\neg"
pos_review_path = r"E:\9Dec2023\Notes\2024_3_26_Naive_Bayes\movie_reviews\pos"

In [5]:
neg_review_files = glob.glob(f"{neg_review_path}\\*.txt")
pos_review_files = glob.glob(f"{pos_review_path}\\*.txt")
len(neg_review_files),len(pos_review_files)

(1000, 999)

#### 2. Preprocessing

In [53]:
review_list_pos_neg = []
### cleaning neg reviews
port_stemer = PorterStemmer()
for file_name in neg_review_files:
    f = open(file_name,"r")
    text = f.read().lower()
    text = re.sub("[^a-z]"," ",text)
    text_list = text.split()
    text =" ".join(text_list)
    ############# text converted into words tokens
    tokens_list = word_tokenize(text)
    # word1 = TextBlob(word)
    # word1.correct().string
    stemmed_text = [port_stemer.stem(token) for token in tokens_list]

    # stemmed_text = [TextBlob(port_stemer.stem(token)).correct().string for token in tokens_list]
    text = " ".join(stemmed_text)
    review_list_pos_neg.append(text)
    
print(len(review_list_pos_neg))
#########################################
for file_name in pos_review_files:
    f = open(file_name,"r")
    text = f.read().lower()
    text = re.sub("[^a-z]"," ",text)
    text_list = text.split()
    text =" ".join(text_list)
    ############# text converted into words tokens
    tokens_list = word_tokenize(text)
    # stemmed_text = [TextBlob(port_stemer.stem(token)).correct().string for token in tokens_list]
    stemmed_text = [port_stemer.stem(token) for token in tokens_list]

    text = " ".join(stemmed_text)
    review_list_pos_neg.append(text)
print(len(review_list_pos_neg))

1000
1999


#### Creat Target column

In [54]:
neg_target = np.zeros(len(neg_review_files),dtype=int)

pos_target = np.ones(len(pos_review_files),dtype=int)
len(neg_target),len(pos_target)

(1000, 999)

In [55]:
y = np.append(neg_target,pos_target)
y = pd.Series(y)
y

0       0
1       0
2       0
3       0
4       0
       ..
1994    1
1995    1
1996    1
1997    1
1998    1
Length: 1999, dtype: int32

In [56]:
review_list_pos_neg[0]

'plot two teen coupl go to a church parti drink and then drive they get into an accid one of the guy die but hi girlfriend continu to see him in her life and ha nightmar what s the deal watch the movi and sorta find out critiqu a mind fuck movi for the teen gener that touch on a veri cool idea but present it in a veri bad packag which is what make thi review an even harder one to write sinc i gener applaud film which attempt to break the mold mess with your head and such lost highway memento but there are good and bad way of make all type of film and these folk just didn t snag thi one correctli they seem to have taken thi pretti neat concept but execut it terribl so what are the problem with the movi well it main problem is that it s simpli too jumbl it start off normal but then downshift into thi fantasi world in which you as an audienc member have no idea what s go on there are dream there are charact come back from the dead there are other who look like the dead there are strang ap

#### 3. Feature Engineering >>> Bag of words

In [57]:
# converting text data into numerical data
cnt_vector = CountVectorizer()
x_cnt_vector = cnt_vector.fit_transform(review_list_pos_neg).toarray()
x_cnt = pd.DataFrame(x_cnt_vector,columns = cnt_vector.get_feature_names_out())
x_cnt.head()

aa  aaa  aaaaaaaaah  aaaaaaaahhhh  aaaaaah  aaaahhh  aah  aaliyah  aalyah  \
0   0    0           0             0        0        0    0        0       0   
1   0    0           0             0        0        0    0        0       0   
2   0    0           0             0        0        0    0        0       0   
3   0    0           0             0        0        0    0        0       0   
4   0    0           0             0        0        0    0        0       0   

   aamir  ...  zuko  zukovski  zulu  zundel  zurg  zweibel  zwick  zwigoff  \
0      0  ...     0         0     0       0     0        0      0        0   
1      0  ...     0         0     0       0     0        0      0        0   
2      0  ...     0         0     0       0     0        0      0        0   
3      0  ...     0         0     0       0     0        0      0        0   
4      0  ...     0         0     0       0     0        0      0        0   

   zyci  zzzzzzz  
0     0        0  
1     0        0  
2     0        0  
3     0        0  
4     0        0  

[5 rows x 25367 columns]

In [58]:
# converting text data into numerical data
cnt_vector = CountVectorizer(min_df = 0.05)
x_cnt_vector = cnt_vector.fit_transform(review_list_pos_neg).toarray()
x_cnt = pd.DataFrame(x_cnt_vector,columns = cnt_vector.get_feature_names_out())
x_cnt.head()

abil  abl  about  abov  absolut  accent  accept  achiev  across  act  ...  \
0     0    0      2     0        0       0       0       0       0    0  ...   
1     0    0      0     0        0       0       0       0       1    2  ...   
2     0    0      0     0        0       0       0       0       0    1  ...   
3     0    1      0     0        0       0       0       0       0    0  ...   
4     0    0      5     0        0       0       0       0       0    0  ...   

   wrong  wrote  ye  year  yet  york  you  young  your  yourself  
0      0      0   0     1    0     0    3      0     2         0  
1      0      0   0     0    0     0    2      0     1         0  
2      1      0   0     0    0     0    2      1     0         0  
3      0      0   0     1    0     0    2      0     0         0  
4      0      0   0     0    1     0    2      0     0         0  

[5 rows x 1201 columns]

In [59]:
# converting text data into numerical data
cnt_vector = CountVectorizer(stop_words= "english",min_df = 0.05)
x_cnt_vector = cnt_vector.fit_transform(review_list_pos_neg).toarray()
x_cnt = pd.DataFrame(x_cnt_vector,columns = cnt_vector.get_feature_names_out())
x_cnt.head()

abil  abl  abov  absolut  accent  accept  achiev  act  action  actor  ...  \
0     0    0     0        0       0       0       0    0       0      1  ...   
1     0    0     0        0       0       0       0    2       1      0  ...   
2     0    0     0        0       0       0       0    1       0      0  ...   
3     0    1     0        0       0       0       0    0       0      1  ...   
4     0    0     0        0       0       0       0    0       0      2  ...   

   wouldn  write  writer  written  wrong  wrote  ye  year  york  young  
0       0      1       0        0      0      0   0     1     0      0  
1       0      0       0        0      0      0   0     0     0      0  
2       0      0       0        1      1      0   0     0     0      1  
3       0      0       0        0      0      0   0     1     0      0  
4       0      1       0        0      0      0   0     0     0      0  

[5 rows x 1016 columns]

### 3.2 TF-IDF

In [60]:
# converting text data into numerical data
tfidf_vector = TfidfVectorizer(stop_words= "english",min_df = 0.05)
x_tfidf_vector = tfidf_vector.fit_transform(review_list_pos_neg).toarray()
x_tfidf = pd.DataFrame(x_tfidf_vector,columns = tfidf_vector.get_feature_names_out())
x_tfidf.head()

abil       abl  abov  absolut  accent  accept  achiev       act    action  \
0   0.0  0.000000   0.0      0.0     0.0     0.0     0.0  0.000000  0.000000   
1   0.0  0.000000   0.0      0.0     0.0     0.0     0.0  0.133265  0.072639   
2   0.0  0.000000   0.0      0.0     0.0     0.0     0.0  0.042769  0.000000   
3   0.0  0.079956   0.0      0.0     0.0     0.0     0.0  0.000000  0.000000   
4   0.0  0.000000   0.0      0.0     0.0     0.0     0.0  0.000000  0.000000   

      actor  ...  wouldn     write  writer   written    wrong  wrote   ye  \
0  0.035826  ...     0.0  0.054633     0.0  0.000000  0.00000    0.0  0.0   
1  0.000000  ...     0.0  0.000000     0.0  0.000000  0.00000    0.0  0.0   
2  0.000000  ...     0.0  0.000000     0.0  0.059508  0.06079    0.0  0.0   
3  0.052370  ...     0.0  0.000000     0.0  0.000000  0.00000    0.0  0.0   
4  0.075763  ...     0.0  0.057767     0.0  0.000000  0.00000    0.0  0.0   

       year  york     young  
0  0.031559   0.0  0.000000  
1  0.000000   0.0  0.000000  
2  0.000000   0.0  0.051319  
3  0.046133   0.0  0.000000  
4  0.000000   0.0  0.000000  

[5 rows x 1016 columns]

#### TF-IDF

In [61]:
x_train,x_test,y_train,y_test = train_test_split(x_tfidf,y,test_size=0.2,random_state=42,stratify=y)

#### 4 Model Training

##### GuassianNB

In [62]:
gnb_model = GaussianNB()
gnb_model.fit(x_train,y_train)

GaussianNB()

In [63]:
# on testing data
y_pred = gnb_model.predict(x_test)
cnf_matrix = confusion_matrix(y_test,y_pred)
print("Confusion matrix\n",cnf_matrix)
cnf_report = classification_report(y_test,y_pred)
print("Classification report is \n",cnf_report)

############ on Training side
y_pred = gnb_model.predict(x_train)
cnf_matrix = confusion_matrix(y_train,y_pred)
print("Confusion matrix\n",cnf_matrix)
cnf_report = classification_report(y_train,y_pred)
print("Classification report is \n",cnf_report)

Confusion matrix
 [[156  44]
 [ 56 144]]
Classification report is 
               precision    recall  f1-score   support

           0       0.74      0.78      0.76       200
           1       0.77      0.72      0.74       200

    accuracy                           0.75       400
   macro avg       0.75      0.75      0.75       400
weighted avg       0.75      0.75      0.75       400

Confusion matrix
 [[704  96]
 [123 676]]
Classification report is 
               precision    recall  f1-score   support

           0       0.85      0.88      0.87       800
           1       0.88      0.85      0.86       799

    accuracy                           0.86      1599
   macro avg       0.86      0.86      0.86      1599
weighted avg       0.86      0.86      0.86      1599



### MultinimialNB

In [64]:
mnb_model = MultinomialNB()
mnb_model.fit(x_train,y_train)

MultinomialNB()

In [65]:
# on testing data
y_pred = mnb_model.predict(x_test)
cnf_matrix = confusion_matrix(y_test,y_pred)
print("Confusion matrix\n",cnf_matrix)
cnf_report = classification_report(y_test,y_pred)
print("Classification report is \n",cnf_report)

############ on Training side
y_pred = mnb_model.predict(x_train)
cnf_matrix = confusion_matrix(y_train,y_pred)
print("Confusion matrix\n",cnf_matrix)
cnf_report = classification_report(y_train,y_pred)
print("Classification report is \n",cnf_report)

Confusion matrix
 [[165  35]
 [ 34 166]]
Classification report is 
               precision    recall  f1-score   support

           0       0.83      0.82      0.83       200
           1       0.83      0.83      0.83       200

    accuracy                           0.83       400
   macro avg       0.83      0.83      0.83       400
weighted avg       0.83      0.83      0.83       400

Confusion matrix
 [[694 106]
 [120 679]]
Classification report is 
               precision    recall  f1-score   support

           0       0.85      0.87      0.86       800
           1       0.86      0.85      0.86       799

    accuracy                           0.86      1599
   macro avg       0.86      0.86      0.86      1599
weighted avg       0.86      0.86      0.86      1599



#### 3. Bernaulli NB

In [68]:
bnb_model= BernoulliNB()
bnb_model.fit(x_train,y_train)

BernoulliNB()

In [69]:
# on testing data
y_pred = bnb_model.predict(x_test)
cnf_matrix = confusion_matrix(y_test,y_pred)
print("Confusion matrix\n",cnf_matrix)
cnf_report = classification_report(y_test,y_pred)
print("Classification report is \n",cnf_report)

############ on Training side
y_pred = bnb_model.predict(x_train)
cnf_matrix = confusion_matrix(y_train,y_pred)
print("Confusion matrix\n",cnf_matrix)
cnf_report = classification_report(y_train,y_pred)
print("Classification report is \n",cnf_report)

Confusion matrix
 [[168  32]
 [ 51 149]]
Classification report is 
               precision    recall  f1-score   support

           0       0.77      0.84      0.80       200
           1       0.82      0.74      0.78       200

    accuracy                           0.79       400
   macro avg       0.80      0.79      0.79       400
weighted avg       0.80      0.79      0.79       400

Confusion matrix
 [[710  90]
 [181 618]]
Classification report is 
               precision    recall  f1-score   support

           0       0.80      0.89      0.84       800
           1       0.87      0.77      0.82       799

    accuracy                           0.83      1599
   macro avg       0.83      0.83      0.83      1599
weighted avg       0.83      0.83      0.83      1599



### CNT

In [70]:
x_train,x_test,y_train,y_test = train_test_split(x_cnt,y,test_size=0.2,random_state=42,stratify=y)

#### GaussianNB

In [71]:
gnb_model = GaussianNB()
gnb_model.fit(x_train,y_train)

GaussianNB()

In [72]:
# on testing data
y_pred = gnb_model.predict(x_test)
cnf_matrix = confusion_matrix(y_test,y_pred)
print("Confusion matrix\n",cnf_matrix)
cnf_report = classification_report(y_test,y_pred)
print("Classification report is \n",cnf_report)

############ on Training side
y_pred = gnb_model.predict(x_train)
cnf_matrix = confusion_matrix(y_train,y_pred)
print("Confusion matrix\n",cnf_matrix)
cnf_report = classification_report(y_train,y_pred)
print("Classification report is \n",cnf_report)

Confusion matrix
 [[160  40]
 [ 80 120]]
Classification report is 
               precision    recall  f1-score   support

           0       0.67      0.80      0.73       200
           1       0.75      0.60      0.67       200

    accuracy                           0.70       400
   macro avg       0.71      0.70      0.70       400
weighted avg       0.71      0.70      0.70       400

Confusion matrix
 [[721  79]
 [266 533]]
Classification report is 
               precision    recall  f1-score   support

           0       0.73      0.90      0.81       800
           1       0.87      0.67      0.76       799

    accuracy                           0.78      1599
   macro avg       0.80      0.78      0.78      1599
weighted avg       0.80      0.78      0.78      1599



##### MultinimialNB

In [73]:
mnb_model = MultinomialNB()
mnb_model.fit(x_train,y_train)

MultinomialNB()

In [74]:
# on testing data
y_pred = mnb_model.predict(x_test)
cnf_matrix = confusion_matrix(y_test,y_pred)
print("Confusion matrix\n",cnf_matrix)
cnf_report = classification_report(y_test,y_pred)
print("Classification report is \n",cnf_report)

############ on Training side
y_pred = mnb_model.predict(x_train)
cnf_matrix = confusion_matrix(y_train,y_pred)
print("Confusion matrix\n",cnf_matrix)
cnf_report = classification_report(y_train,y_pred)
print("Classification report is \n",cnf_report)

Confusion matrix
 [[160  40]
 [ 36 164]]
Classification report is 
               precision    recall  f1-score   support

           0       0.82      0.80      0.81       200
           1       0.80      0.82      0.81       200

    accuracy                           0.81       400
   macro avg       0.81      0.81      0.81       400
weighted avg       0.81      0.81      0.81       400

Confusion matrix
 [[681 119]
 [132 667]]
Classification report is 
               precision    recall  f1-score   support

           0       0.84      0.85      0.84       800
           1       0.85      0.83      0.84       799

    accuracy                           0.84      1599
   macro avg       0.84      0.84      0.84      1599
weighted avg       0.84      0.84      0.84      1599



##### Bernaulli NB

In [76]:
bnb_model= BernoulliNB()
bnb_model.fit(x_train,y_train)

BernoulliNB()

In [77]:
# on testing data
y_pred = bnb_model.predict(x_test)
cnf_matrix = confusion_matrix(y_test,y_pred)
print("Confusion matrix\n",cnf_matrix)
cnf_report = classification_report(y_test,y_pred)
print("Classification report is \n",cnf_report)

############ on Training side
y_pred = bnb_model.predict(x_train)
cnf_matrix = confusion_matrix(y_train,y_pred)
print("Confusion matrix\n",cnf_matrix)
cnf_report = classification_report(y_train,y_pred)
print("Classification report is \n",cnf_report)

Confusion matrix
 [[168  32]
 [ 51 149]]
Classification report is 
               precision    recall  f1-score   support

           0       0.77      0.84      0.80       200
           1       0.82      0.74      0.78       200

    accuracy                           0.79       400
   macro avg       0.80      0.79      0.79       400
weighted avg       0.80      0.79      0.79       400

Confusion matrix
 [[710  90]
 [181 618]]
Classification report is 
               precision    recall  f1-score   support

           0       0.80      0.89      0.84       800
           1       0.87      0.77      0.82       799

    accuracy                           0.83      1599
   macro avg       0.83      0.83      0.83      1599
weighted avg       0.83      0.83      0.83      1599



In [ ]:
from nltk.stem import PorterStemmer,LancasterStemmer
from nltk.stem import WordNetLemmatizer

In [32]:
pst = PorterStemmer()
pst.stem("acting")

'act'

In [33]:
pst = PorterStemmer()
pst.stem("action")

'action'

In [34]:
pst = PorterStemmer()
pst.stem("having")

'have'

In [35]:
pst = PorterStemmer()
pst.stem("played")

'play'

In [36]:
pst = PorterStemmer()
pst.stem("playing")

'play'

#### Lemmatizer

In [37]:
word_net_lemma = WordNetLemmatizer()
word_net_lemma.lemmatize("playing",pos="v")

'play'

In [38]:
word_net_lemma = WordNetLemmatizer()
word_net_lemma.lemmatize("accepted",pos="v")

'accept'

In [39]:
pst = PorterStemmer()
pst.stem("science")

'scienc'

In [40]:
word_net_lemma = WordNetLemmatizer()
word_net_lemma.lemmatize("science",pos="v")

'science'

##### spelling correction

In [41]:
from textblob import TextBlob
word = "scienc"
word1 = TextBlob(word)
word1.correct().string

'science'

In [43]:
text = "and do they make things entertaining , thrilling or even engaging , in the meantime ? "
tokens = word_tokenize(text)
tokens

['and',
 'do',
 'they',
 'make',
 'things',
 'entertaining',
 ',',
 'thrilling',
 'or',
 'even',
 'engaging',
 ',',
 'in',
 'the',
 'meantime',
 '?']